spring:
  application:
    name: proxy-service

server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
              
zuul:
  routes:
    customer:
      path: /reporte/**
      serviceId: reporte-service
      
security:
  oauth2:
    resource:
      filter-order: 3