CREATE TABLE USUARIO(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
	NOMBRE VARCHAR(128),
	CLAVE VARCHAR(128),
	EMAIL VARCHAR(128),
	HABILITADO BOOLEAN,
	VENCIMIENTO TIMESTAMP
);

CREATE TABLE ROL(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
	NOMBRE VARCHAR(128),
	DESCRIPCION VARCHAR(256)
);

CREATE TABLE ROLUSUARIO(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
	USUARIO BIGINT,
	ROL BIGINT
);

ALTER TABLE ROLUSUARIO
	ADD FOREIGN KEY (USUARIO)
	REFERENCES USUARIO(ID)
;

ALTER TABLE ROLUSUARIO
	ADD FOREIGN KEY (ROL)
	REFERENCES ROL(ID)
;