server:
  port: 8080
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
      
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: reporte-service